version: "3.9"
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      -  mongo_db:/data/db

  backend:
    build: ./back-end
    container_name: academy_pharma_container
    ports:
      -  '5000:5000'
    environment:
      DATABASE_CONNECTION : mongodb://mongodb:27017/academy_bjit
      JWT_SECRET_KEY: anykeythatfits
      FRONTEND_URI: http://localhost:3000/
    depends_on:
      -  mongodb
  frontend:
    build: ./front-end
    ports:
      -  '3000:3000'
    stdin_open: true
    tty: true
volumes:
  mongo_db: {}

